### ISSUE TITLE
Unable to reproduce the result

### ISSUE THREAD

**Issue by XgDuan** [shaohua0116/demo2program#1]
I have downloaded the code in this repo and downloaded the pretrained model from https://ctolib.com/shaohua0116-demo2program.html, the program, however,  is unable to evaluate(or train). 
The error information is
```
nvalidArgumentError (see above for traceback): indices[15,0] = 51 is not in [0, 51)
         [[Node: Program_Decoder/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Program_Decoder/Token_Embedding/embedding_map"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Program_Decoder/Token_Embedding/embedding_map/read, Program_Decoder/concat, Program_Decoder/embedding_lookup/axis)]]
```

The reason is that in the `LSTM_Decoder` function, the definition of `s_token` iis conflicted with the definition of `embedding_lookup`: `s_token's == token_dim + 1` exceeds the size of `embedding_map`.
I have tried to redefine `s_tokens` as `token_dim` or to enlarge the size of `embedding_map`, both are runable, but unable to reproduce the results in the paper.

**Comment by XgDuan** [comment]
Sorry for the last issue, and I have somehow reproduced the results. Just redefine `s_tokens` as `s_tokens = token_dim`.

**Comment by HyeonwooNoh** [comment]
Thanks for pointing out this issue, we will update the code.

**Comment by HeyZeu5** [comment]
I'm getting the same issue with the Action_Decoder.

`tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 13 is not in [0, 13)
	 [[Node: Action_Decoder_8/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Action_Decoder/Token_Embedding/embedding_map"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Action_Decoder/Token_Embedding/embedding_map/read, Action_Decoder_8/concat)]]`
