### ISSUE TITLE
Unable to reproduce the results on Vizdoom

### ISSUE THREAD

**Issue by XgDuan** [shaohua0116/demo2program#3]
Hi, I found it hard to reproduce the results on the `Vizdoom` dataset. I use the default arguments except `num_k=25`, but the results are far from the one mentioned in your paper(seq accu=53% in the paper, while our result is about 40%). So could you provide us with the hyperparameters you use to train a `full model` on `Vizdoom`?

**Comment by HyeonwooNoh** [comment]
Hi, could you elaborate which hyperparameter setting did you use for the visdoom experiment?

**Comment by XgDuan** [comment]
![image](https://user-images.githubusercontent.com/13313976/46659028-a7a00980-cbe6-11e8-86b1-d5b01d3b162e.png)
We keep most of the hyperparameters the same as your code as shown in the foregoing screenshot, except that we set `num_k=25` as in your paper(BTW, `num_k=10` results in a similar bad model).

**Comment by HyeonwooNoh** [comment]
I see. How do you eval result after training? Have you tried eval with pretrained checkpoint?

**Comment by XgDuan** [comment]
No, I have not run your checkpoint. Because of the bug I mentioned in another issue, I made a minor change to your code, which means that the checkpoint is unable to load.
I recommend that you clone your github code and run it, which, in my opinion, has a bug(someone else has encountered the same problem(another open issue), and I have given a solution in my another closed issue). After that, would you then provide me with another checkpoint?

**Comment by XgDuan** [comment]
Thank you very much

**Comment by HyeonwooNoh** [comment]
Okay I will check it today and reply before the end of tomorrow. Thank you for your patience

**Comment by HyeonwooNoh** [comment]
Hi, we checked the issue and found that checkpoint is unable to load. 
I think the code is broken while cleaning up, so trying to fix it based on previous commit (which is not included in this repository).
We will update as soon as we fix this issue.

**Comment by XgDuan** [comment]
Thanks for your time and effort

**Comment by HyeonwooNoh** [comment]
Hi, sorry for the delay.
Did you try running our code with different hyperparameters?
I recommend to try with batch_size = 32 / batch_size = 64.

**Comment by HyeonwooNoh** [comment]
Hi, I just pushed a fix to the code. 
In the relational network based aggregation part, there should be a residual connection.
I checked that we could reproduce result with the uploaded checkpoint.
I think now it should reproduce the reported result.
Could you please confirm this?

**Comment by XgDuan** [comment]
Thanks a lot, we will have a try.

**Comment by HyeonwooNoh** [comment]
We updated the readme with more detailed instruction for reproducing our result. We confirmed that we could reproduce reported result with the described commands. Please follow the description and let us know if it still does not work.
